### ISSUE TITLE
Yada Node Continues to Crash Windows 10 Home

### ISSUE THREAD

**Issue by Rogue-Miner** [pdxwebdev/yadacoin#117]
Setting up Yada Master Node so 3 computers, all with Windows 10 Home. Each continue to crash randomly, caught the error this time and Matt asked me to share. Please let me know if you have question, Discord Rogue_Miner. 

![Screenshot 2024-08-14 202048](https://github.com/user-attachments/assets/48f2951b-f2b0-4732-9b63-126209d34cfc)
![Screenshot 2024-08-14 211309](https://github.com/user-attachments/assets/41250032-f941-41a0-9304-df5a216d3243)

**Comment by pdxwebdev** [comment]
Fixed in commit `77d48be15cdd9e216a7e2fe8f18247b2c9d0c565`
