### ISSUE TITLE
Remove transactions from mempool

### ISSUE THREAD

**Issue by username1565** [pdxwebdev/yadacoin#41]
Hello. I see some transactions are pending, for a long time,
how is possible to remove them from mempool, on the yadacoin full node?

**Comment by pdxwebdev** [comment]
There was a bug that caused this. You'll have to open your mongo console and remove the pending transactions manually.

Here's how to do that:

`mongo`
`use yadacoin`
`db.miner_transactions.remove({id: 'MEUCIQD+rZyvf0dRPDR7ASvI1YDNi0QYUk28Xykg8YiiLQd4pgIgbnDD7JFwLrO5dtwLBbjIeGeY3kuvAo023tK6J36n/XE='})
and repeat that last line for the other ids`

**Comment by username1565** [comment]
How can I try to re-send the pending transaction, to see the status of this transaction?
I want to be sure, that I'll remove from mongodb, only invalid transactions, and try to re-send the valid tx's.

**Comment by pdxwebdev** [comment]
@username1565 I've pushed a fix for this. It will be in the next release.

**Comment by pdxwebdev** [comment]
Fixed.
