### ISSUE TITLE
Combine all workers by address on pool stats api

### ISSUE THREAD

**Issue by pdxwebdev** [pdxwebdev/yadacoin#42]
Currently, miners must paste each individual address.worker to get stats.

We want miners to paste and address and return stats for all workers.

This includes listing all workers and their hash rate.

**Comment by CC-coin** [comment]
Also, it would be nice to include the Accepted/ Stale/ Invalid shares on the stats for total and each worker.

**Comment by pdxwebdev** [comment]
Feature added.
